source "http://rubygems.org"

gem "rake"
gem "rspec"
gem "cucumber"
gem "capybara"
gem "capybara-mechanize"
gem "phantomjs"
gem "poltergeist"
gem "rest-client"
gem "nokogiri"
gem "tinder", github: "technoweenie/tinder", branch: "faraday-0.9"