Feature: redirector

Smoke tests

# Generated by redirector/tools/generate_smokey_tests.sh Tue  7 May 2013 12:16:15 BST

  @normal
  Scenario: Redirect for businesslink from alliance-leicestercommercialbank.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://alliance-leicestercommercialbank.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_anguilla from anguilla.fco.gov.uk
    Given I am benchmarking
    When I visit "http://anguilla.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/anguilla"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from aol.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://aol.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_britishantarcticterritory from britishantarcticterritory.fco.gov.uk
    Given I am benchmarking
    When I visit "http://britishantarcticterritory.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/organisations/british-antarctic-territory"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_britishembassyinireland from britishembassyinireland.fco.gov.uk
    Given I am benchmarking
    When I visit "http://britishembassyinireland.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/ireland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_centralcontent from centralcontent.fco.gov.uk
    Given I am benchmarking
    When I visit "http://centralcontent.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/foreign-commonwealth-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for decc_ceo from ceo.decc.gov.uk
    Given I am benchmarking
    When I visit "http://ceo.decc.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/community-energy"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_elearning from elearning.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://elearning.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/browse/business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_falklandislands from falklandislands.fco.gov.uk
    Given I am benchmarking
    When I visit "http://falklandislands.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/falkland-islands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dh_immunisation from immunisation.dh.gov.uk
    Given I am benchmarking
    When I visit "http://immunisation.dh.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/public-health-england/series/immunisation"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_improve from improve.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://improve.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/growing-your-business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_lrc from lrc.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://lrc.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/browse/business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dh_mediacentre from mediacentre.dh.gov.uk
    Given I am benchmarking
    When I visit "http://mediacentre.dh.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-of-health"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for decc_mrws from mrws.decc.gov.uk
    Given I am benchmarking
    When I visit "http://mrws.decc.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/policies/managing-the-use-and-disposal-of-radioactive-and-nuclear-substances-and-waste"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from msn.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://msn.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for decc_og from og.decc.gov.uk
    Given I am benchmarking
    When I visit "http://og.decc.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-of-energy-climate-change"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from online.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://online.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_ukwelcomes from online.ukwelcomes.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://online.ukwelcomes.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/uk-welcomes-business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dh_publications from publications.dh.gov.uk
    Given I am benchmarking
    When I visit "http://publications.dh.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-of-health"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from sagestartup.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://sagestartup.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from simplybusiness.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://simplybusiness.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_turksandcaicosislands from turksandcaicosislands.fco.gov.uk
    Given I am benchmarking
    When I visit "http://turksandcaicosislands.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/turks-and-caicos-islands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukcoe from ukcoe.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukcoe.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uk-delegation-to-council-of-europe"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukeu from ukeu.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukeu.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uk-representation-to-the-eu"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukforiranians from ukforiranians.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukforiranians.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/iran"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinafghanistan from ukinafghanistan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinafghanistan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/afghanistan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinalbania from ukinalbania.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinalbania.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/albania"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinalgeria from ukinalgeria.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinalgeria.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/algeria"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinangola from ukinangola.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinangola.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/angola"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinargentina from ukinargentina.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinargentina.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/argentina"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinarmenia from ukinarmenia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinarmenia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/armenia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinaustralia from ukinaustralia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinaustralia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/australia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinaustria from ukinaustria.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinaustria.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/austria"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinazerbaijan from ukinazerbaijan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinazerbaijan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/azerbaijan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbahrain from ukinbahrain.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbahrain.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/bahrain"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbangladesh from ukinbangladesh.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbangladesh.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/bangladesh"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbarbados from ukinbarbados.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbarbados.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/barbados"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbelarus from ukinbelarus.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbelarus.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/belarus"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbelgium from ukinbelgium.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbelgium.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/belgium"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbelize from ukinbelize.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbelize.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/belize"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbih from ukinbih.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbih.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/bosnia-and-herzegovina"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbolivia from ukinbolivia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbolivia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/bolivia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbotswana from ukinbotswana.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbotswana.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/botswana"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbrazil from ukinbrazil.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbrazil.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/brazil"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbrunei from ukinbrunei.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbrunei.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/brunei"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbulgaria from ukinbulgaria.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbulgaria.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/bulgaria"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinburma from ukinburma.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinburma.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/burma"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinbvi from ukinbvi.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinbvi.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/british-virgin-islands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincambodia from ukincambodia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincambodia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/cambodia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincameroon from ukincameroon.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincameroon.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/cameroon"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincanada from ukincanada.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincanada.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/canada"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincayman from ukincayman.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincayman.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/cayman-islands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinchile from ukinchile.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinchile.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/chile"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinchina from ukinchina.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinchina.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/china"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincolombia from ukincolombia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincolombia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/colombia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincostarica from ukincostarica.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincostarica.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/costa-rica"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincroatia from ukincroatia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincroatia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/croatia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincuba from ukincuba.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincuba.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/cuba"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukincyprus from ukincyprus.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukincyprus.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/cyprus"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinczechrepublic from ukinczechrepublic.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinczechrepublic.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/czech-republic"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukindenmark from ukindenmark.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukindenmark.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/denmark"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukindominicanrepublic from ukindominicanrepublic.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukindominicanrepublic.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/dominican-republic"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukindprk from ukindprk.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukindprk.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/north-korea"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukindrc from ukindrc.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukindrc.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/democratic-republic-of-congo"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinecuador from ukinecuador.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinecuador.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/ecuador"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinegypt from ukinegypt.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinegypt.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/egypt"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinelsalvador from ukinelsalvador.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinelsalvador.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/el-salvador"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukineritrea from ukineritrea.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukineritrea.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/eritrea"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinestonia from ukinestonia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinestonia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/estonia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinethiopia from ukinethiopia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinethiopia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/ethiopia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinfiji from ukinfiji.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinfiji.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/fiji"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinfinland from ukinfinland.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinfinland.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/finland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinfrance from ukinfrance.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinfrance.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/france"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukingambia from ukingambia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukingambia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/gambia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukingeorgia from ukingeorgia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukingeorgia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/georgia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukingermany from ukingermany.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukingermany.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/germany"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinghana from ukinghana.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinghana.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/ghana"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukingreece from ukingreece.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukingreece.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/greece"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinguatemala from ukinguatemala.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinguatemala.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/guatemala"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinguyana from ukinguyana.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinguyana.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/guyana"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinholysee from ukinholysee.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinholysee.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/holy-see"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinhongkong from ukinhongkong.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinhongkong.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/hong-kong"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinhungary from ukinhungary.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinhungary.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/hungary"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukiniceland from ukiniceland.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukiniceland.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/iceland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinindia from ukinindia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinindia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/india"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinindonesia from ukinindonesia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinindonesia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/indonesia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukiniraq from ukiniraq.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukiniraq.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/iraq"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinisrael from ukinisrael.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinisrael.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/israel"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinitaly from ukinitaly.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinitaly.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/italy"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinjamaica from ukinjamaica.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinjamaica.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/jamaica"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinjapan from ukinjapan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinjapan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/japan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinjerusalem from ukinjerusalem.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinjerusalem.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/jerusalem"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinjordan from ukinjordan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinjordan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/jordan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinkenya from ukinkenya.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinkenya.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/kenya"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinkosovo from ukinkosovo.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinkosovo.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/kosovo"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinkuwait from ukinkuwait.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinkuwait.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/kuwait"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinkz from ukinkz.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinkz.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/kazakhstan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinlaos from ukinlaos.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinlaos.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/laos"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinlatvia from ukinlatvia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinlatvia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/latvia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinlebanon from ukinlebanon.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinlebanon.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/lebanon"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinlibya from ukinlibya.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinlibya.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/libya"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinlithuania from ukinlithuania.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinlithuania.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/lithuania"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinluxembourg from ukinluxembourg.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinluxembourg.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/luxembourg"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmacedonia from ukinmacedonia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmacedonia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/macedonia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmadagascar from ukinmadagascar.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmadagascar.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/madagascar"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmalawi from ukinmalawi.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmalawi.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/malawi"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmalaysia from ukinmalaysia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmalaysia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/malaysia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmaldives from ukinmaldives.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmaldives.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/maldives"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmalta from ukinmalta.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmalta.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/malta"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmauritius from ukinmauritius.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmauritius.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/mauritius"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmexico from ukinmexico.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmexico.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/mexico"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmoldova from ukinmoldova.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmoldova.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/moldova"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmongolia from ukinmongolia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmongolia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/mongolia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmontenegro from ukinmontenegro.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmontenegro.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/montenegro"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmontserrat from ukinmontserrat.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmontserrat.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/montserrat"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmorocco from ukinmorocco.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmorocco.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/morocco"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinmozambique from ukinmozambique.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinmozambique.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/mozambique"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnamibia from ukinnamibia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnamibia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/namibia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnepal from ukinnepal.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnepal.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/nepal"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnewzealand from ukinnewzealand.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnewzealand.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/new-zealand"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnigeria from ukinnigeria.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnigeria.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/nigeria"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnl from ukinnl.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnl.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/netherlands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinnorway from ukinnorway.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinnorway.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/norway"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinoman from ukinoman.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinoman.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/oman"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinpakistan from ukinpakistan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinpakistan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/pakistan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinpanama from ukinpanama.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinpanama.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/panama"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinperu from ukinperu.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinperu.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/peru"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinpng from ukinpng.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinpng.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/papua-new-guinea"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinpoland from ukinpoland.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinpoland.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/poland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinportugal from ukinportugal.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinportugal.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/portugal"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinqatar from ukinqatar.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinqatar.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/qatar"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinrok from ukinrok.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinrok.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/south-korea"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinromania from ukinromania.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinromania.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/romania"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinrussia from ukinrussia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinrussia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/russia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinrwanda from ukinrwanda.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinrwanda.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/rwanda"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsaudiarabia from ukinsaudiarabia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsaudiarabia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/saudi-arabia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsenegal from ukinsenegal.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsenegal.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/senegal"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinserbia from ukinserbia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinserbia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/serbia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinseychelles from ukinseychelles.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinseychelles.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/seychelles"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsierraleone from ukinsierraleone.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsierraleone.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/sierra-leone"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsingapore from ukinsingapore.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsingapore.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/singapore"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinslovakia from ukinslovakia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinslovakia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/slovakia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinslovenia from ukinslovenia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinslovenia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/slovenia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsolomonislands from ukinsolomonislands.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsolomonislands.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/solomon-islands"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsomalia from ukinsomalia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsomalia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/somalia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsouthafrica from ukinsouthafrica.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsouthafrica.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/south-africa"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsouthsudan from ukinsouthsudan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsouthsudan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/south-sudan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinspain from ukinspain.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinspain.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/spain"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsrilanka from ukinsrilanka.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsrilanka.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/sri-lanka"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsudan from ukinsudan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsudan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/sudan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsweden from ukinsweden.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsweden.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/sweden"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinswitzerland from ukinswitzerland.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinswitzerland.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/switzerland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinsyria from ukinsyria.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinsyria.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/syria"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintaiwan from ukintaiwan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintaiwan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/taiwan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintajikistan from ukintajikistan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintajikistan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/tajikistan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintanzania from ukintanzania.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintanzania.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/tanzania"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinthailand from ukinthailand.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinthailand.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/thailand"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinthephilippines from ukinthephilippines.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinthephilippines.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/philippines"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintimorleste from ukintimorleste.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintimorleste.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/timor-leste"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintt from ukintt.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintt.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/trinidad-and-tobago"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukintunisia from ukintunisia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukintunisia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/tunisia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinturkey from ukinturkey.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinturkey.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/turkey"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinturkmenistan from ukinturkmenistan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinturkmenistan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/turkmenistan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinuae from ukinuae.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinuae.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/united-arab-emirates"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinuganda from ukinuganda.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinuganda.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uganda"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinukraine from ukinukraine.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinukraine.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/ukraine"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinuruguay from ukinuruguay.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinuruguay.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uruguay"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinusa from ukinusa.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinusa.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/usa"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinuzbekistan from ukinuzbekistan.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinuzbekistan.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uzbekistan"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinvenezuela from ukinvenezuela.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinvenezuela.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/venezuela"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinvietnam from ukinvietnam.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinvietnam.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/vietnam"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinyemen from ukinyemen.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinyemen.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/yemen"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinzambia from ukinzambia.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinzambia.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/zambia"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukinzimbabwe from ukinzimbabwe.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukinzimbabwe.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/zimbabwe"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukmissiongeneva from ukmissiongeneva.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukmissiongeneva.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uk-mission-to-the-un-geneva"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_uknato from uknato.fco.gov.uk
    Given I am benchmarking
    When I visit "http://uknato.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uk-joint-delegation-to-nato"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco_ukun from ukun.fco.gov.uk
    Given I am benchmarking
    When I visit "http://ukun.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/world/uk-mission-to-the-united-nations-new-york"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_ukwelcomes from ukwelcomes.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://ukwelcomes.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/uk-welcomes-business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_ukwelcomes from upload.ukwelcomes.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://upload.ukwelcomes.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/uk-welcomes-business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for oag from www.advocategeneral.gov.uk
    Given I am benchmarking
    When I visit "http://www.advocategeneral.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/office-of-the-advocate-general-for-scotland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for ago from www.ago.gov.uk
    Given I am benchmarking
    When I visit "http://www.ago.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/attorney-generals-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for ago from www.attorneygeneral.gov.uk
    Given I am benchmarking
    When I visit "http://www.attorneygeneral.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/attorney-generals-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for bis from www.bis.gov.uk
    Given I am benchmarking
    When I visit "http://www.bis.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-business-innovation-skills"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from www.business.gov.uk
    Given I am benchmarking
    When I visit "http://www.business.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from www.businesslink.co.uk
    Given I am benchmarking
    When I visit "http://www.businesslink.co.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from www.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://www.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink from www.businesslink.org
    Given I am benchmarking
    When I visit "http://www.businesslink.org/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for cabinetoffice from www.cabinetoffice.gov.uk
    Given I am benchmarking
    When I visit "http://www.cabinetoffice.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/cabinet-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dclg from www.communities.gov.uk
    Given I am benchmarking
    When I visit "http://www.communities.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-communities-and-local-government"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dcms from www.culture.gov.uk
    Given I am benchmarking
    When I visit "http://www.culture.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-culture-media-sport"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dclg from www.dclg.gov.uk
    Given I am benchmarking
    When I visit "http://www.dclg.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "http://www.communities.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dcms from www.dcms.gov.uk
    Given I am benchmarking
    When I visit "http://www.dcms.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-culture-media-sport"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for decc from www.decc.gov.uk
    Given I am benchmarking
    When I visit "http://www.decc.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-of-energy-climate-change"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dfid from www.dfid.gov.uk
    Given I am benchmarking
    When I visit "http://www.dfid.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-international-development"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dft from www.dft.gov.uk
    Given I am benchmarking
    When I visit "http://www.dft.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-for-transport"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dh from www.dh.gov.uk
    Given I am benchmarking
    When I visit "http://www.dh.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/department-of-health"
    And the elapsed time should be less than 2 seconds

  @urgent
  Scenario: Redirect for directgov from www.direct.gov.uk
    Given I am benchmarking
    When I visit "http://www.direct.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for dpm from www.dpm.cabinetoffice.gov.uk
    Given I am benchmarking
    When I visit "http://www.dpm.cabinetoffice.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/deputy-prime-ministers-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for ukef from www.ecgd.gov.uk
    Given I am benchmarking
    When I visit "http://www.ecgd.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/export-credit-guarantee-department"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for fco from www.fco.gov.uk
    Given I am benchmarking
    When I visit "http://www.fco.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/foreign-commonwealth-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for homeoffice from www.homeoffice.gov.uk
    Given I am benchmarking
    When I visit "http://www.homeoffice.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/home-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for ago from www.lslo.gov.uk
    Given I am benchmarking
    When I visit "http://www.lslo.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/attorney-generals-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for mod from www.mod.uk
    Given I am benchmarking
    When I visit "http://www.mod.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/ministry-of-defence"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for nio from www.nio.gov.uk
    Given I am benchmarking
    When I visit "http://www.nio.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/northern-ireland-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for number10 from www.number10.gov.uk
    Given I am benchmarking
    When I visit "http://www.number10.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/prime-ministers-office-10-downing-street"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for oag from www.oag.gov.uk
    Given I am benchmarking
    When I visit "http://www.oag.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/office-of-the-advocate-general-for-scotland"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for scotlandoffice from www.scotlandoffice.gov.uk
    Given I am benchmarking
    When I visit "http://www.scotlandoffice.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/scotland-office"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for walesoffice_cymru from www.swyddfa.cymru.gov.uk
    Given I am benchmarking
    When I visit "http://www.swyddfa.cymru.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/wales-office.cy"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for ukef from www.ukexportfinance.gov.uk
    Given I am benchmarking
    When I visit "http://www.ukexportfinance.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/export-credit-guarantee-department"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for businesslink_ukwelcomes from www.ukwelcomes.businesslink.gov.uk
    Given I am benchmarking
    When I visit "http://www.ukwelcomes.businesslink.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/uk-welcomes-business"
    And the elapsed time should be less than 2 seconds

  @normal
  Scenario: Redirect for walesoffice from www.walesoffice.gov.uk
    Given I am benchmarking
    When I visit "http://www.walesoffice.gov.uk/" without following redirects
    Then I should get a 301 status code
    And I should get a location of "https://www.gov.uk/government/organisations/wales-office"
    And the elapsed time should be less than 2 seconds

